// Code generated by "stringer -type Type"; DO NOT EDIT.

package licensecheck

import "strconv"

const _Type_name = "AGPLApacheBSDCCGPLJSONMITUnlicenseZlibOther"

var _Type_index = [...]uint8{0, 4, 10, 13, 15, 18, 22, 25, 34, 38, 43}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
