// Code generated by "stringer -type Type"; DO NOT EDIT.

package licensecheck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AGPL-0]
	_ = x[Apache-1]
	_ = x[BSD-2]
	_ = x[CC-3]
	_ = x[EPL-4]
	_ = x[GPL-5]
	_ = x[JSON-6]
	_ = x[MIT-7]
	_ = x[Unlicense-8]
	_ = x[Zlib-9]
	_ = x[Other-10]
}

const _Type_name = "AGPLApacheBSDCCEPLGPLJSONMITUnlicenseZlibOther"

var _Type_index = [...]uint8{0, 4, 10, 13, 15, 18, 21, 25, 28, 37, 41, 46}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
